"""add schema's name to Product model for query purpose

Revision ID: 0f93ccaf0e0a
Revises: 671d5cec30d8
Create Date: 2024-10-25 21:59:32.591041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f93ccaf0e0a'
down_revision = '671d5cec30d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_product'),
    schema='ms_products'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products', schema='ms_products')
    # ### end Alembic commands ###
